name: "Request Action"
description: "Perform HTTP API requests in GitHub Actions to interact with external services and capture responses."
author: Muh Faris
branding:
  icon: "zap"
  color: "blue"
inputs:
  url: # id of input
    description: "The URL of the API you want to make a request to"
    required: true
  headers:
    description: "A JSON-formatted string containing the headers to include in the request"
    default: '{"Content-Type": "application/json"}'
  body:
    description: "The request body data (if applicable)."
  method:
    description: "The HTTP method to use for the request (default is POST if not specified)."
    default: "POST"
outputs:
  response-status: # id of output
    description: "The HTTP status code of the API response"
  response-data:
    description: "The JSON-formatted response data from the API"
runs:
  using: "node16"
  main: "dist/index.js"
