name: "Request Action"
description: "This GitHub Action allows you to make HTTP API requests as part of your workflow. You can use it to interact with external services and capture the response data for further use in your workflow. This README provides instructions on how to set up and use this action in your GitHub Actions workflow."
inputs:
  url: # id of input
    description: "The URL of the API you want to make a request to"
    required: true
  headers:
    description: "A JSON-formatted string containing the headers to include in the request"
    default: '{"Content-Type": "application/json"}'
  body:
    description: "The request body data (if applicable)."
  method:
    description: "The HTTP method to use for the request (default is POST if not specified)."
    default: "POST"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: "index.js"
