name: API Request Action
on: [push]
jobs:
  api-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Choose an appropriate Node.js version
      - name: Install dependencies
        run: npm install
      # GET request
      - name: Make GET API Request
        id: get-request
        uses: ./dist
        with:
          url: "https://jsonplaceholder.typicode.com/todos"
          headers: '{"Content-Type":"application/json"}'
          method: "GET"
      - name: Display GET API Response Status
        run: |
          echo "GET Response Status: ${{ steps.get-request.outputs.response-status }}"
      - name: Display GET API Response Data
        run: |
          echo "GET Response Data: ${{ steps.get-request.outputs.response-data }}"
      # POST request
      - name: Make POST API Request
        id: post-request
        uses: ./dist
        with:
          url: "https://jsonplaceholder.typicode.com/todos"
          headers: '{"Content-Type":"application/json"}'
          body: |
            {
              "userId": 1,
              "id": 201,
              "title": "new todo",
              "completed": false
            }
          method: "POST"
      - name: Display POST API Response Status
        run: |
          echo "POST Response Status: ${{ steps.post-request.outputs.response-status }}"
      - name: Display POST API Response Data
        run: |
          echo "POST Response Data: ${{ steps.post-request.outputs.response-data }}"
      # PUT request
      - name: Make PUT API Request
        id: put-request
        uses: ./dist
        with:
          url: "https://jsonplaceholder.typicode.com/todos/1"
          headers: '{"Content-Type":"application/json"}'
          body: |
            {
              "userId": 1,
              "id": 1,
              "title": "updated todo",
              "completed": true
            }
          method: "PUT"
      - name: Display PUT API Response Status
        run: |
          echo "PUT Response Status: ${{ steps.put-request.outputs.response-status }}"
      - name: Display PUT API Response Data
        run: |
          echo "PUT Response Data: ${{ steps.put-request.outputs.response-data }}"
